### ISSUE TITLE
Call math functions from UDFs

### ISSUE THREAD

**Issue by pearu** [Quansight/omnisci#81]
Originally raised in https://github.com/Quansight/pearu-issues/issues/20

Example case:
```
@omnisci
def mysin(x):
    return math.sin(x)  # or numpy.sin(x)

query = 'select x, mysin(x) from mytable'
# executing query should return sin values
```
Todo:
- [x] identify the problem if any
- [x] fix it

Background: UDF definitions should be able to use any functions that are made available in the omniscidb LLVM IR module linkage phase.

**Comment by pearu** [comment]
https://github.com/xnd-project/rbc/issues/40
https://github.com/xnd-project/rbc/issues/38
https://github.com/xnd-project/rbc/issues/32
https://github.com/xnd-project/rbc/issues/31

**Comment by guilhermeleobas** [comment]
- [x] xnd-project/rbc#40 - Add NumPy types to rbc typesystem.
- [x] xnd-project/rbc#38 - List of NumPy math functions that Omniscidb supports. Closed in favor of xnd-project/rbc#31
- [x] xnd-project/rbc#32 - Resolves the infinity recursion when registering UDFs with specific names.
- [ ] xnd-project/rbc#31 - Contains a list of numpy functions that Omniscidb supports.

We can close this issue and open a new open for xnd-project/rbc#31
