### ISSUE TITLE
RBC maintenance

### ISSUE THREAD

**Issue by pearu** [Quansight/omnisci#84]
- [x] https://github.com/xnd-project/rbc/issues/3 - Replace mapd with omnisci
- [x] https://github.com/xnd-project/rbc/issues/14 - Add flake8 to CI jobs
- [x] https://github.com/xnd-project/rbc/issues/11 - Support servers with different targets
- [ ] https://github.com/xnd-project/rbc/issues/4 - Failure with complex arguments when in Win32
- [x] https://github.com/xnd-project/rbc/issues/15 - Generate documentation from docstring
- [x] https://github.com/xnd-project/rbc/issues/20 - Release 0.2.1
- [x] https://github.com/xnd-project/rbc/issues/18 - Retrieve thrift configuration from omniscidb server
- [ ] https://github.com/xnd-project/rbc/issues/13 - Evaluate notebooks as a part of testing suite
See https://github.com/xnd-project/rbc/issues for up-to-date list.

**Comment by pearu** [comment]
https://github.com/omnisci/omniscidb-internal/pull/4133 implements support for retrieving server thrift typemap via `get_device_parameters` endpoint.

**Comment by kcpevey** [comment]
Closing because the issue tracking is done in the rbc issue tracker.
